#!/usr/bin/env python3
"""Generate base_instances.yaml and lazy_instances.yaml from the shipped
descriptive_instances.yaml.

The repo ships only ``scripts/descriptive_instances.yaml`` (the SWE-agent batch
config for the *descriptive* prompt variant). The base/lazy variants reuse the
exact same tasks, env, and ``problem_statement.id`` — only the natural-language
``problem_statement.text`` differs. We build them by swapping in the text of the
matching ``problems/<variant>_problems/<repo>/<id>.txt`` file (looked up by id).

Requires PyYAML (present in the SWE-agent venv). Run e.g.:

    .swe-venv/bin/python scripts/gen_instances.py
"""
from __future__ import annotations

import copy
import glob
import os
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit(
        "PyYAML not found. Run with the SWE-agent venv python, e.g.\n"
        "    .swe-venv/bin/python scripts/gen_instances.py"
    )

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPTS_DIR)
SRC_YAML = os.path.join(SCRIPTS_DIR, "descriptive_instances.yaml")
VARIANTS = ("base", "lazy")  # descriptive already exists


def problem_text(variant: str, instance_id: str) -> str:
    """Return the prompt text for ``instance_id`` in ``variant``.

    The id is the problem-file stem, unique across repos, so a glob across the
    variant's per-repo subdirs uniquely locates it.
    """
    pattern = os.path.join(
        REPO_ROOT, "problems", f"{variant}_problems", "*", f"{instance_id}.txt"
    )
    matches = glob.glob(pattern)
    if len(matches) != 1:
        raise FileNotFoundError(
            f"{variant}: expected exactly 1 problem file for id {instance_id!r}, "
            f"found {len(matches)}: {matches}"
        )
    with open(matches[0], "r", encoding="utf-8") as fh:
        return fh.read().strip()


def main() -> int:
    with open(SRC_YAML, "r", encoding="utf-8") as fh:
        descriptive = yaml.safe_load(fh)

    if not isinstance(descriptive, list) or not descriptive:
        sys.exit(f"{SRC_YAML} did not parse to a non-empty list")

    ids = [inst["problem_statement"]["id"] for inst in descriptive]
    print(f"descriptive: {len(ids)} instances")

    for variant in VARIANTS:
        out = []
        for inst in descriptive:
            iid = inst["problem_statement"]["id"]
            new_inst = copy.deepcopy(inst)
            new_inst["problem_statement"]["text"] = problem_text(variant, iid)
            out.append(new_inst)

        # Sanity: same ids, same order, count preserved.
        assert [i["problem_statement"]["id"] for i in out] == ids, "id mismatch"

        out_path = os.path.join(SCRIPTS_DIR, f"{variant}_instances.yaml")
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(f"# Auto-generated by scripts/gen_instances.py ({variant} variant)\n")
            yaml.safe_dump(out, fh, sort_keys=False, default_flow_style=False, width=10**9, allow_unicode=True)
        print(f"wrote {out_path}: {len(out)} instances")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
